#ifndef	_NOVATEK_I2C_TS_H
#define	_NOVATEK_I2C_TS_H

#define	TRUE		1
#define	ATTB_PIN_LOW	0

#define PROTOCOL_ADDR 0
#define PROTOCOL_LEN /*0x3C*/(POINTS_MAX*PROTOCOL_POINT_LEN)
#define PROTOCOL_HEAD_LEN 0

#define PROTOCOL_POINT_LEN 6

#define I2C_STARTTCH_READ       0
#define I2C_STARTTCH_POINT1     (I2C_STARTTCH_READ + PROTOCOL_HEAD_LEN + PROTOCOL_POINT_LEN)
#define I2C_STARTTCH_POINT2     (I2C_STARTTCH_READ + PROTOCOL_HEAD_LEN + (PROTOCOL_POINT_LEN<<1))

#define POINTS_MAX	20

#define BUTTON_PID_START 21
#define BUTTON_MASK (1<<4)

#endif
