#ifndef	_PIXCIR_I2C_TS_H
#define	_PIXCIR_I2C_TS_H

#define	TRUE		1
#define	ATTB_PIN_LOW	0

#define PROTOCOL_ADDR 0
#define PROTOCOL_LEN 27
#define PROTOCOL_HEAD_LEN 2

#define PROTOCOL_POINT_LEN 5

#define I2C_STARTTCH_READ       0
#define I2C_STARTTCH_POINT2     (I2C_STARTTCH_READ + PROTOCOL_HEAD_LEN + (PROTOCOL_POINT_LEN<<1))

#define POINTS_MAX	5

enum {
    PIXCIR_CALIBRATE_UNKNOW,
    PIXCIR_CALIBRATING,
    PIXCIR_CALIBRATE_SUCCESS,
    PIXCIR_CALIBRATE_FAILED,
};

#define MAX_CALIBRATE_CHECKTIME (20*HZ)

#endif
